### ISSUE TITLE
Is it possible to access the created_at date of an event in apply()?

### ISSUE THREAD

**Issue by PJKerrigan** [awto-rs/awto-es#4]
Forgive me if the answer to this question is obvious, I'm a beginner when it comes to Rust.

I'm looking at moving an event-sourced system using Laravel (via spatie/laravel-event-sourcing) to Rust, but there are differences between the libraries.

Is it possible to access the event metadata, particularly the date the event was created, inside of the aggregate's apply function?

**Comment by tqwewe** [comment]
That's a good question I haven't considered before. Currently there's no way to access event metadata in apply. One solution would be to store a timestamp in the event itself.

I'm actually in the process of rewriting thalo entirely, and have been working on it for a few weeks now. I'll try to push what I have soon to a different branch. For this reason though, I have to warn you that using Thalo currently wouldn't provide a lot since its missing a few things. You're better off waiting for me to push the rewrite, or look into another library for the time being. But if you are just playing around then it should be fine.

Does Laravel event sourcing support reading event metadata when applying events to an aggregate?

**Comment by PJKerrigan** [comment]
Thanks for the response!

The PHP library I mentioned in my post does allow that. The events inherit from a specific class ShouldBeStored, which has the metadata assigned when they are recorded, before being handed to the aggregate apply method and then projectors and reactors.

I don't mind storing dates and so-on inside the events themselves, it's just quite useful for created_at/updated_at fields on projections.

I'll wait for the rewrite. This seems like a really cool project. 👍

**Comment by tqwewe** [comment]
Hey @PJKerrigan 

I've pushed the rewrite under the [runtime-rewrite](https://github.com/thalo-rs/thalo/tree/runtime-rewrite) branch!
I'm pretty happy with how things have turned out, though building the examples requires a few steps since wasm components are still very eary stage.

Let me know if you have any questions if you decide to try it out, I'd love to help you with it. Or if you've joined the Discord, feel free to send a message there.

**Comment by tqwewe** [comment]
Closing for now as the rewrite allows for this information and has been merged to main
